FLASK_APP=vqg.py
DATABASE_URL=sqlite:///vqg.db
FLASK_RUN_HOST=0.0.0.0
FLASK_RUN_PORT=5000
PROGRESS_COMPLETION=7
COMPLETION_URL=https://app.prolific.co/submissions/complete?cc=6A92B1A5
COMPLETION_CODE =6A92B1A5