"""start

Revision ID: 8708a381843a
Revises: 
Create Date: 2021-07-06 11:39:14.671354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8708a381843a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_set', sa.String(length=5), nullable=True),
    sa.Column('img_url', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_data_set'), 'image', ['data_set'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prolific_id', sa.String(length=64), nullable=True),
    sa.Column('study_id', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('attn_check', sa.String(length=12), nullable=True),
    sa.Column('vision_check', sa.String(length=8), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('current_image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('q_num', sa.Integer(), nullable=True),
    sa.Column('q_content', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_image_id'), 'annotation', ['image_id'], unique=False)
    op.create_index(op.f('ix_annotation_user_id'), 'annotation', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotation_user_id'), table_name='annotation')
    op.drop_index(op.f('ix_annotation_image_id'), table_name='annotation')
    op.drop_table('annotation')
    op.drop_table('user')
    op.drop_index(op.f('ix_image_data_set'), table_name='image')
    op.drop_table('image')
    # ### end Alembic commands ###
