"""adding user column for current image id

Revision ID: a687db8a983a
Revises: 92dcbf1bd5d0
Create Date: 2021-06-15 15:49:18.279171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a687db8a983a'
down_revision = '92dcbf1bd5d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'image', ['current_image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'current_image_id')
    # ### end Alembic commands ###
